### ISSUE TITLE
Minor modification

### ISSUE THREAD

**Issue by phreakinggeek** [cjcotton/init-kibana#1]
Not a big deal, but you might want to change the var for DAEMON to DAEMON=$KIBANA_BIN/$NAME rather than having to modify the settings in more than one place... personal preference, nbd. Thanks for posting this script! :+1:

**Comment by cottonbeckfield** [comment]
Haha, I agree with you. I actually originally did that, but it caused an error and the daemon didn't start. It was late at night, so I pulled the tragic 'Hrng...I'll come back to it'. I'll leave this open, and in a few days push out a corrected version with your suggestion! :)

**Comment by cottonbeckfield** [comment]
Went ahead and pushed the updated code & README to reflect DAEMON=$KIBANA_BIN/$NAME 
Did a mini-test, all seemed well and Kibana4 started without issue.

Thanks again :+1: !
