### ISSUE TITLE
doesn't start on ubuntu 15.10 - kibana 4.3.1

### ISSUE THREAD

**Issue by washingon** [cjcotton/init-kibana#4]
Jan 23 16:42:26 yaz systemd[1]: Started Kibana 4.
Jan 23 16:42:26 yaz systemd[2268]: kibana.service: Failed at step USER spawning /opt/kibana/node/bin/node: No such process
Jan 23 16:42:26 yaz systemd[1]: kibana.service: Main process exited, code=exited, status=217/USER
Jan 23 16:42:26 yaz systemd[1]: kibana.service: Unit entered failed state.
Jan 23 16:42:26 yaz systemd[1]: kibana.service: Failed with result 'exit-code'.

**Comment by cottonbeckfield** [comment]
Per the README.md;

> This script runs Kibana4 on RHEL6 / CENTOS6 as a non-root user. You can specify the user you wish to run Kibana4 as.

You are running systemd, and this is an init script (Rhel6 still uses init). However, if you are looking for a systemd script, here is an alternative link with someone who posted a working systemd script for kibana in the comments: https://discuss.elastic.co/t/run-kibana-as-service-on-centos/23971/4

Closing this out, as it's not relevant to this particular script.

Cheers, good luck!
