### ISSUE TITLE
Version of Kibana

### ISSUE THREAD

**Issue by mativillagra** [cjcotton/init-kibana#5]
Hello, 

Can you please share what version of kibana do you used with for this init - script to work. 

Thanks.

**Comment by cottonbeckfield** [comment]
This is for Kibana4 on Centos6 (or RHEL6) systems.

**Comment by mativillagra** [comment]
Thanks for you answer, but can you be more specific in what version do you test it out. 

I'm trying to used with version kibana-4.4.2-linux-x64  on Red Hat Enterprise Linux Server release 6.8 (Santiago) without success 

Thanks in advance.

**Comment by cottonbeckfield** [comment]
Unfortunately I wrote this 3 years ago and did not write that down. 

However, I do remember it was on RHEL 6.5.

Typically you should get some sort of error though when an init script is failing. Has it returned one?

Most people have had issues relating to the fact that while the process will run as the alternative user (app_kibana in my case), you still need sudo permissions if you're installing it to /etc/init.d and that will require sudo permissions to run the service. 

Sorry I can't be of more help!
